name: Test

on:
  pull_request:
    paths:
        - 'extensions/oidc/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: antonengelhardt/rust-docker-tools
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: cd extensions/oidc

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo Deny
        uses: EmbarkStudios/cargo-deny-action@v1

      - name: Run tests
        run: |
          rustc --version && cargo --version
          cargo clippy
          cargo test --workspace --verbose
